require:
  - rubocop-rspec
  - rubocop-performance

Rails:
  Enabled: true

Layout/LineLength:
  Max: 120

AllCops:
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/*'
    - 'node_modules/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
