default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= Rails.application.credentials.database_url %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
